In [1]:
import pandas as pd
airports_dataframe = pd.read_csv('flight_data.csv')
airports_dataframe

airports_dataframe.dropna(inplace=True)

In [2]:
x = airports_dataframe.loc[:, ['DISTANCE', 'CRS_ELAPSED_TIME']]
#"CRS_ELAPSED_TIME" 是航空業中的一個術語，代表著航班的計劃飛行時間，通常以分鐘為單位。
y = airports_dataframe.loc[:, ['ARR_DELAY']]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=63)

In [3]:
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

In [4]:
def compute_cost(x, y, w, b):
    '''
    returns:
    cost is corresponding w and b

    Parameters:
    x, y(training data)
    w, b(a array of weight, a constant of bias)
    '''
    y_predict = (x * w).sum(axis=1) + b
    cost = ((y - y_predict)**2).mean()

    return cost

In [5]:
import numpy as np
w = np.array([100, 100])
b = 0
compute_cost(x_train, y_train, w, b)

7914915679.577116

In [6]:
y_predict = (x_train * w).sum(axis=1) + b
b_gradient = (y_predict - y_train).mean()

w_gradient = np.zeros(x_train.shape[1])
for i in range(x_train.shape[1]):
    w_gradient[i] = (x_train[:, i] * (y_predict - y_train)).mean()

w_gradient, b_gradient

(array([67903066.07330847, 11246998.55392869]), 76323.58213256484)

In [7]:
def compute_gradient(x, y, w, b):
    '''
    Returns:
    w_gradient(微分結果, a array), b_gradient(微分結果)
    
    Parameters:
    x, y(data)
    w, b(a array of weight, a constant of bias)
    '''
    y_predict = (x * w).sum(axis=1) + b
    b_gradient = (y_predict - y).mean()

    w_gradient = np.zeros(x.shape[1])
    for i in range(x.shape[1]):
        w_gradient[i] = (x[:, i] * (y_predict - y)).mean()

    return w_gradient, b_gradient

In [8]:
w = np.array([100, 100])
b = 1
learning_rate = 0.000002

w_gradient, b_gradient = compute_gradient(x_train, y_train, w, b)

print(compute_cost(x_train, y_train, w, b))

w = w - w_gradient * learning_rate
b = b - b_gradient * learning_rate
print(compute_cost(x_train, y_train, w, b))
print(w, b)

7915068327.741382
310924812.7971986
[-35.80742602  77.50577027] 0.8473508357348704


In [9]:
np.set_printoptions(formatter={'float': '{: .2e}'.format})
#需要轉換格式因為w以及w_gradient是一個陣列形態
def gradient_descent(x, y, w_init, b_init, learning_rate, cost_function, gradient_function, run_iter, p_iter=1000):
    
    c_hist = []
    w_hist = []
    b_hist = []
    
    w = w_init
    b = b_init

    for i in range(run_iter + 1):
        w_gradient, b_gradient = gradient_function(x, y, w, b)

        w = w - w_gradient*learning_rate
        b = b - b_gradient*learning_rate
        cost = cost_function(x, y, w, b)

        w_hist.append(w)
        b_hist.append(b)
        c_hist.append(cost)

        if i%p_iter == 0:
            print(f"Iteration {i:5} : Cost {cost: .4e}, w: {w}, b: {b: .2e}, w_gradient: {w_gradient}, b_gradient: {b_gradient: .2e}")

    return w, b, w_hist, b_hist, c_hist

In [10]:
w_init = np.array([100, 100])
b_init = 0
learning_rate = 0.000002
run_iter = 20000
p_iter = 2000

w_final, b_final, w_hist, b_hist, c_hist = gradient_descent(x_train, y_train, w_init, b_init, learning_rate, compute_cost, compute_gradient, run_iter, p_iter)

Iteration     0 : Cost  3.1092e+08, w: [-3.58e+01  7.75e+01], b: -1.53e-01, w_gradient: [ 6.79e+07  1.12e+07], b_gradient:  7.63e+04
Iteration  2000 : Cost  1.3330e+05, w: [-3.11e+00  1.88e+01], b: -1.74e+00, w_gradient: [-1.13e+03  6.87e+03], b_gradient:  1.77e+02
Iteration  4000 : Cost  8.0153e+03, w: [-7.27e-01  4.42e+00], b: -2.11e+00, w_gradient: [-2.62e+02  1.59e+03], b_gradient:  4.09e+01
Iteration  6000 : Cost  1.3161e+03, w: [-1.76e-01  1.09e+00], b: -2.20e+00, w_gradient: [-6.07e+01  3.67e+02], b_gradient:  9.35e+00
Iteration  8000 : Cost  9.5784e+02, w: [-4.88e-02  3.19e-01], b: -2.22e+00, w_gradient: [-1.40e+01  8.49e+01], b_gradient:  2.05e+00
Iteration 10000 : Cost  9.3868e+02, w: [-1.94e-02  1.40e-01], b: -2.22e+00, w_gradient: [-3.25e+00  1.96e+01], b_gradient:  3.68e-01
Iteration 12000 : Cost  9.3766e+02, w: [-1.26e-02  9.91e-02], b: -2.22e+00, w_gradient: [-7.51e-01  4.55e+00], b_gradient: -2.25e-02
Iteration 14000 : Cost  9.3761e+02, w: [-1.10e-02  8.95e-02], b: -2.2

In [11]:
w_final, b_final

(array([-1.05e-02,  8.67e-02]), -2.2180629630870876)

In [12]:
y_predict = (x_test * w_final).sum(axis=1) + b_final
y_predict

array([ 1.24e+00,  1.58e+00,  9.95e-01,  1.75e+00,  5.65e-01,  2.12e+00,
        1.10e+00,  1.08e+00,  9.03e-01,  7.48e-01,  1.80e-01,  2.88e+00,
        2.12e+00, -8.67e-04,  1.44e+00,  1.89e+00,  9.01e-01,  4.69e-01,
        2.78e+00,  5.07e-01,  2.18e+00, -3.48e-02,  1.11e+00,  2.99e-01,
        1.21e+00,  1.24e+00,  6.69e-01,  1.63e+00,  1.80e+00,  2.33e+00,
        6.34e-01,  1.86e+00,  1.68e+00,  4.03e-01,  8.54e-01,  2.57e+00,
        1.65e+00,  1.04e+00,  7.86e-01,  1.25e+00,  8.87e-01,  1.34e+00,
        7.14e-01,  9.36e-01,  1.24e+00,  1.27e+00,  1.49e+00,  1.25e+00,
        1.04e+00,  2.04e-01,  8.74e-01,  4.41e-01,  9.97e-01,  1.13e+00,
        2.88e+00,  3.03e+00, -2.71e-01,  5.62e-01,  1.03e+00,  3.61e+00,
        6.04e-01,  3.03e+00,  6.69e-01,  1.61e+00,  1.47e+00,  5.05e-01,
        1.73e+00,  8.81e-01,  1.56e+00,  2.62e+00,  5.48e-01,  6.99e-01,
        4.62e-01,  1.25e+00,  9.51e-01,  4.27e-01,  7.67e-01, -1.29e-01,
        1.24e+00,  8.91e-01,  1.77e+00,  8.17e-01, 

In [13]:
compute_cost(x_test, y_test, w_final, b_final)

398.85744715360073

In [14]:
from sklearn import metrics
print(f"Mean Squared Error: {metrics.mean_squared_error(y_test, y_predict)}")

Mean Squared Error: 398.65327176126794


In [15]:
y_test = pd.DataFrame(y_test)
y_predict = pd.DataFrame(y_predict)

### 使用 pandas.concat() 方法將兩個 Pandas 系列合併為一個 DataFrame

In [16]:
y_predict_and_y_test = pd.concat([y_test, y_predict], axis=1)

new_columns = ['y test', 'y predict']
y_predict_and_y_test.columns = new_columns
y_predict_and_y_test

y test  y predict
0     -12.0   1.244096
1      26.0   1.575352
2      -6.0   0.995183
3       1.0   1.748171
4      -5.0   0.565336
..      ...        ...
145    92.0   1.271897
146    -1.0   0.834208
147     2.0   0.613499
148   -11.0   1.467858
149    -8.0  -0.116347

[150 rows x 2 columns]

In [17]:
# 1670, 225
# 580, 105
x_real = np.array([[1670, 225], [580, 105]])
y_real = (w_final*x_real).sum(axis=1) + b_final
y_real

array([-2.71e-01,  7.86e-01])