In [1]:
import torch

In [2]:
x = torch.tensor(87)
print(x)
print(x.shape)#顯示每個維度中有幾個數
print(x.ndim)#維度

tensor(87)
torch.Size([])
0


In [3]:
x = torch.tensor([1, 2, 3])
print(x)
print(x.shape)#顯示每個維度中有幾個數
print(x.ndim)#維度

tensor([1, 2, 3])
torch.Size([3])
1


In [4]:
x = torch.tensor([[1, 2, 3],
                [4, 5, 6]])
print(x)
print(x.shape)#顯示每個維度中有幾個數
print(x.ndim)#維度

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
2


In [5]:
torch.manual_seed(86)
x = torch.rand(2, 3, 4)#用來設定每個維度中有幾個數
x

tensor([[[0.8674, 0.2262, 0.0158, 0.3520],
         [0.0753, 0.8784, 0.1758, 0.3905],
         [0.2213, 0.5736, 0.0050, 0.1305]],

        [[0.8398, 0.9041, 0.9417, 0.9396],
         [0.1421, 0.1628, 0.6087, 0.6335],
         [0.0900, 0.8420, 0.6592, 0.5055]]])

In [6]:
x = torch.zeros(3, 4)#用來設定每個維度中有幾個數
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
x = torch.ones(2, 3, 4)#用來設定每個維度中有幾個數
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
x = torch.arange(0, 11, 2)
x

tensor([ 0,  2,  4,  6,  8, 10])

In [9]:
x = torch.tensor([0.1, 0.2, 0.3],
                dtype=None,
                device=None,
                requires_grad=True)
x.dtype, x.device, x.requires_grad

(torch.float32, device(type='cpu'), True)

In [10]:
x = torch.tensor([[[0.1, 0.2, 0.3],
                [0.4, 0.5, 0.6]]])
x[0][0][0]#用來設定要輸出維度中的第幾個數

tensor(0.1000)

In [11]:
x = torch.tensor([[0.1, 0.2, 0.3],
                [0.4, 0.5, 0.6]])
x / 10

tensor([[0.0100, 0.0200, 0.0300],
        [0.0400, 0.0500, 0.0600]])

In [12]:
x = torch.tensor([[0.1, 0.2, 0.3],
                [0.4, 0.5, 0.6]])

y = torch.tensor([[1, 2, 3],
                [4, 5, 6]])

x / y

tensor([[0.1000, 0.1000, 0.1000],
        [0.1000, 0.1000, 0.1000]])

In [13]:
x = torch.tensor([[1, 2],
                [3, 4],
                [5, 6]])

y = torch.tensor([[1, 2, 3],
                [4, 5, 6]])

torch.matmul(x, y)#矩陣相乘

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [14]:
x = torch.tensor([[1, 2],
                [3, 4],
                [5, 6]])
x.T#進行轉置

tensor([[1, 3, 5],
        [2, 4, 6]])

In [15]:
x = torch.arange(0, 10)
x.reshape(2, 5, 1)#進行維度修改但是出來的個數必須和原先的個數相同

tensor([[[0],
         [1],
         [2],
         [3],
         [4]],

        [[5],
         [6],
         [7],
         [8],
         [9]]])

In [16]:
import numpy as np
array = np.array([1, 2, 3])
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3]), tensor([1, 2, 3], dtype=torch.int32))

In [17]:
tensor = torch.tensor([1, 2, 3])
array = tensor.numpy()
tensor, array

(tensor([1, 2, 3]), array([1, 2, 3], dtype=int64))